# Generated by Django 3.1.2 on 2020-11-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201106_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profileimg', verbose_name='عکس'),
        ),
    ]
