# Generated by Django 3.1.1 on 2020-09-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
