# Generated by Django 3.1.1 on 2020-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_data_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس دسته بندی')),
                ('position', models.IntegerField(verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(verbose_name='زمان انتشار مقاله'),
        ),
        migrations.AlterField(
            model_name='data',
            name='paragraph',
            field=models.TextField(default='', verbose_name='محتوا مقاله'),
        ),
        migrations.AlterField(
            model_name='data',
            name='postadby',
            field=models.CharField(max_length=100, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='data',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='آدرس مقاله'),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان مقاله'),
        ),
    ]
