# Generated by Django 3.1.1 on 2020-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200927_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='category',
            field=models.ManyToManyField(to='portfolio.Category', verbose_name='دسته بندی'),
        ),
    ]
