# Generated by Django 3.1.1 on 2020-09-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_data_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.ManyToManyField(blank=True, to='portfolio.Category', verbose_name='دسته بندی'),
        ),
    ]
