# Generated by Django 3.1.1 on 2020-10-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200928_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='portfolio.category', verbose_name='زیر دسته'),
        ),
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.Category', verbose_name='دسته بندی'),
        ),
    ]
