# Generated by Django 3.1.1 on 2020-10-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201010_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='postadby',
        ),
    ]
