# Generated by Django 3.1.1 on 2020-10-14 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_data_postadby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار مقاله'),
        ),
    ]
