# Generated by Django 3.1.1 on 2020-10-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20201014_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='p', max_length=1),
        ),
    ]
