# Generated by Django 3.1.1 on 2020-10-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده')], default='p', max_length=1, verbose_name='وضعیت'),
        ),
    ]
