# Generated by Django 3.1.1 on 2020-10-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20201022_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideimage',
            options={'verbose_name': 'اسلاید', 'verbose_name_plural': 'اسلاید ها'},
        ),
    ]
