# Generated by Django 3.1.1 on 2020-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20201022_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slideimage',
            options={'ordering': ['position'], 'verbose_name': 'اسلاید', 'verbose_name_plural': 'اسلاید ها'},
        ),
        migrations.AddField(
            model_name='slideimage',
            name='position',
            field=models.IntegerField(default='1', verbose_name='جایگاه'),
        ),
    ]
