# Generated by Django 3.1.1 on 2020-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20201022_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideimage',
            name='position',
            field=models.IntegerField(verbose_name='جایگاه'),
        ),
    ]
