# Generated by Django 3.1.1 on 2020-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20201022_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideimage',
            name='position',
            field=models.IntegerField(unique=True, verbose_name='جایگاه'),
        ),
    ]
