# Generated by Django 3.1.1 on 2020-10-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20201023_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
    ]
