# Generated by Django 3.1.2 on 2020-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20201110_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='portfolio.IPAddress', verbose_name='بازدید ها'),
        ),
    ]
