# Generated by Django 3.1.2 on 2020-11-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20201114_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آی پی', 'verbose_name_plural': 'آی پی ها'},
        ),
    ]
